# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: etth
  - /task: forecasting
  - /optimizer: adamw
  - /scheduler: plateau

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: min

encoder:
  _name_: linear
  bias: False
#  - _name_: time
#    timeenc: ${dataset.timeenc}

decoder:
  _name_: sequence
  mode: last

# This dataset is super prone to overfitting so we check validation more often
trainer:
  val_check_interval: 0.2
