defaults:
  - layer: s4

_name_: model
d_model: 256
n_layers: 2
transposed: false
dropout: 0.0
tie_dropout: false
prenorm: true

residual: R

pool:
  _name_: pool
  stride: 1
  expand: null
norm: layer
track_norms: true # Logs to wandb

# Optional encoder/decoder, e.g. add positional embeddings or padding masks
encoder: null
decoder: null
